### ISSUE TITLE
Question regarding the regexp

### ISSUE THREAD

**Issue by helpermethod** [sindresorhus/strip-url-auth#5]
Hi, thank you for this great little library!

I'm currently porting this over to Lua, and I was wondering about that part of the regexp 

    [^@/]

Why is the  `/` part of the negated group? Is it to avoid excessive backtracking?

Thanks in advance?

**Comment by sindresorhus** [comment]
See https://github.com/sindresorhus/strip-url-auth/commit/1512abb70cdde75a0818f3177e7f243869cb5b8b
